### ISSUE TITLE
license file for github enterprise

### ISSUE THREAD

**Issue by thojansen** [githubteacher/cloaked-octo-shame#68]
@brntbeer

The question came up in which cases it makes sense to maintain license files internally on GitHub Enterprise. Maybe you have a few examples to shed some light into this. I could only see cases where you move stuff back and forth from the external to the internal instance or to make it transparent that a project really belongs to the company (IP wise).

**Comment by brntbeer** [comment]
One of my initial thoughts on this is that the license from the start of a project protects not only the developers working on it, but the company as well.  If there was no license, there's technically no way to say who the project belongs to. Does it belong to the person doing the most Lines of Code changes? Does it belong to the company because it's under their organization (even on enterprise)? If that project is also forked to be put under an individual's name, who owns the original IP?

Lastly, if you end up open sourcing a project later, you'd want to ensure a license is added before doing that. It's best to ensure no one could say "well it had no license when **I** found it!"

**Comment by thojansen** [comment]
Thanks for your thoughts on this. I will discuss this internally.
